### ISSUE TITLE
Address Single Pixel Inundation Issue

### ISSUE THREAD

**Issue by BrianAvant** [NOAA-OWP/inundation-mapping#333]
While developing the Categorical FIM datasets, we have noticed an issue consistent across many AHPS sites where inundation along a portion of the stream is restricted to a single pixel width. There are probably multiple reasons why this is occurring. The purpose of this ticket is to diagnose and fix as many of the occurrences as we can. Further tickets may be created to address this issue depending on the findings of this task. 

- [x] Develop tool to detect elevation drops (#408)
- [x] Resolve thalweg drops resulting from lateral thalweg adjustment (#409)
- [x] Replace raster.py with rasterio package (#18)

Issues that still remain:

### Disagreements between NWM and derived NHDPlus HR stream networks

1. FIM 3 input stream network uses the `ToNode/FromNode` and LevelPath attributes to traverse the HR NHDPlus stream network in an attempt to match the density of the NWM stream network used for producing flows. This does not do any vetting of the stream path to ensure that there are no gaps, artificial paths, and other considerations used to convert the NHDPlus medium resolution stream network to the NWM routlink file. It is observed in many cases where the subset HR network will follow an adjacent artificial path, especially below dams. Irrigation lines sometimes cut through multiple catchments. The NHDPlus has attributes to remove these types of segments from the dataset (`FType`/`FCode`) but the dataset is still in progress and is not mature enough to rely on these attributes for our purposes.

2. FIM 3 input stream network does not include braided stream segments. Differences in catchment delineation, braided segment selection of HR vs NWM, and major changes in the stream network geometry make mapping and crosswalking challenging in these areas. 

   Instead of trying to resolve these types of issues within the FIM workflow, it would probably be better to use the same starting network (spatial resolution and density) for both models to derive flow and inundation libraries.

### Distributed networks

  Besides the issues mentioned in the previous point, inundation mapping at highly braided networks are poor due to the simplified way that NWM routes flow through these areas. The current NWM v2.1 configuration selects a single segment to receive 100% of the upstream flow in distributed sections of the network. Alternate segments can still have some flow accumulating from within their own catchments. This simplification is reasonable for flow routing but will likely not adequately represent the needs of FIM.

  NWS LID LMDN5 Action Stage - HUC 13020102
  ![image](https://user-images.githubusercontent.com/20129718/122089789-bba35c80-cdcc-11eb-8627-05ba516146a4.png)

### Steep Terrain

  - FIM 3 does poorly in some areas where there is steep terrain and narrow canyon walls. This is in part likely due to resolution limitations of the input data.
  - True elevation drops below dams can be greater than 5 meters and several cases are observed where this causes single pixel inundation directly below the dam and even sections much further downstream. We could look at easing the elevation gradient in these areas but this could have undesirable side effects. One task we could do to help with this specific issue would be to enforce a break in the DEM derived stream network at dams. Doing this would ensure the catchments didn't contain a mix of higher and lower elevations which compromises the REM.

### Very small streams
  - In some cases, limitations in the resolution of input data prevent adequate representation of inundation. We will need higher resolution elevation data to resolve this case.

### Missing/Bad input data
  - It seems that several sites around the Mexico/US and Canadian/US borders perform quite poorly. It is possible that this is related to partial or incomplete data in these areas. Salt Lake City is an example of this. There are several issues going on that make it challenging to untangle.
  Salt Lake City, NWS LID CCSU1 Action Stage - HUC 16020204
  ![image](https://user-images.githubusercontent.com/20129718/122093197-6bc69480-cdd0-11eb-937d-b68c4754cba1.png)

### Misc
  There are several other cases that would need further investigation to resolve. There may be commonality in the root cause of many of the issues related to single pixel inundation but this requires more analysis and I am not sure at the moment this would be the best return on investment.

  - Stream below dam follows correct path but inundation is mapped primarily on diversion channel (MS):
NWS LID FWLC2 Action Stage - HUC 11020005
![image](https://user-images.githubusercontent.com/20129718/122089454-649d8780-cdcc-11eb-8605-0d1bbd5b6036.png)

  - Streams with high sinuosity: Limitations in the vector representation of stream networks could also partially explain single pixel inundation in some areas as well.
  NWS LID LPSC2 Action Stage - HUC 14080105
  ![image](https://user-images.githubusercontent.com/20129718/122091094-0e314880-cdce-11eb-94b3-28db7971b6c3.png)

  - Sinks adjacent to stream: This was partially resolved with setting a elevation threshold on the lateral thalweg adjustment but there are still some places where single pixel inundation remains. In general, there should probably be a "rule" in FIM 3 that limits or eliminates situations where there is inundation within a catchment that does not connect back to the stream. We can probably resolve this in the hydroconditioning.
  NWS LID GATU1 Action Stage - HUC 16020102
  ![image](https://user-images.githubusercontent.com/20129718/122092577-b398ec00-cdcf-11eb-8f14-0484e78a6019.png)

  - Stream confluences: This is something that we were seeing in FIM 2 and would probably be wise to reach out the the ESRI Arc Hydro team. At the confluence of two tributaries, significant differences (> 5 meters) in thalweg elevation cause an immediate drop to the thalweg path of the higher stream. My initial hypothesis what that this was the majority of the single pixel inundation issues but it turns out that there are only a few instances in FIM 3.

  - False continuity in derived stream network: Sometimes nearby streams are joined together during the derivation of the FIM stream network. In this example near Scottsdale, AZ, a sharp, unnatural HUC 8 boundary intersects a MS headwater stream segment and it is rerouted to a nearby stream,
  NWS LID IDXA3 Action Stage - HUC 15060106 
  ![image](https://user-images.githubusercontent.com/20129718/122095893-89e1c400-cdd3-11eb-9835-5d0fd656c68f.png)

## Screenshots

![image](https://user-images.githubusercontent.com/20129718/112870915-5751e600-9084-11eb-8940-69f25f086c92.png)

**Comment by BrianAvant-NOAA** [comment]
Check nws_lid='CAMN4' for single pixel inundation related to large drop in thalweg elevation during hydroconditioning.

![image](https://user-images.githubusercontent.com/20129718/115446413-cc748f00-a1dc-11eb-9f21-88f97cf72355.png)
