### ISSUE TITLE
[21pt] (ON HOLD) API Upgrades and Add to Dev 2

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#469]
- [ ] Get it running on dev2 as a stand alone (dev2 only)
 - [ ] Get it running on dev2 and USC3 working together
 - [ ] Change naming convention in code to differentiate between dev machine and prod versions.
 - [ ] Small adjustments to UI to tell which enviro is being used (MAAS versus Dev) (careful on names, paths, etc)
 - [ ] Small code re-org
 - [ ] Check if Cancel button works (appears not too)
 - [ ] Clean up output log formatting, hard to read
 - [ ] Review error handling system, especially in light of new error handling within FIM_Run.sh
 - [ ] Check memlog.txt as it grows perpetually
 - [ ] Keep GMS in mind when changing code.
 - [ ] See if we can parallelize copies files over to dev at the end
 - [ ] Test, then test, then test, then test some more.  :)
 - [ ] Document, including setup and config

**Comment by RobHanna-NOAA** [comment]
No longer applicable in light of FIM4
