### ISSUE TITLE
[21pt] Issues around NHD "sinks"

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/inundation-mapping#852]
Our flow routing workflow does not account for NHD sinks. Therefore, DEM-derived flowlines that pass sinks will get crosswalked to an incorrect NWM feature id. 

As a solution, I'm thinking that we could use the NHD sinks dataset to effectively stop the DEM-derived reaches from flowing past them. We may not be able to use all of the sink dataset, so we should look at the attributes to see how we can make sure that we're only stopping flow at the correct points. Using something like `Purpose Description = 'BurnLineEvent network end'` might work.

### Tasks:
- [x] Add a download script for the NHD sinks in `data/nhd_plus/`
    - [x] Find best data source for the sinks - preferably directly from USGS NHD+
- [x] Determine whether the sinks dataset should be filtered down to a certain type
- [x] Ensure that the locations of all of the sinks we're going to use are coincident with the terminal end of a NWM streamline
- [x] Write workflow to remove segments of the `dem_derived_reaches` that are downstream of sinks
    - [x] Should be after the [streamnet step](https://github.com/NOAA-OWP/inundation-mapping/blob/5a201355d79804dbcc8d5ba1345adc7ec73b6ee8/src/delineate_hydros_and_produce_HAND.sh#L73)
    - [x] Branch 0
    - [x] GMS branches

**Comment by CarsonPruitt-NOAA** [comment]
Download the sink data for testing:
```
sys.path.append('/foss_fim/data')
from esri import ESRI_REST
nhd_pnt_url = "https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer/0/query"
sinks = ESRI_REST.query(nhd_url, f="pjson", where="FTYPE=450", returnGeometry="true", outFields="*", outSR="5070" )
```

**Comment by CarsonPruitt-NOAA** [comment]
ESRI also has a NHD Plus service [here](https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/NHDPlusV21/FeatureServer), but I'm thinking that the USGS source listed above is probably the more authoritative.

**Comment by CarsonPruitt-NOAA** [comment]
That's unfortunate. The layer that was matching up with the NWM streamlines was this ESRI one:
https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/NHDPlusV21/FeatureServer

Can you see if you can find the original data source where ESRI pulls this data from? I'd like to pull directly from USGS NHD instead of using ESRI as an intermediary if possible. I'll update the task list on this ticket.

**Comment by mluck** [comment]
The ESRI data (circles, below) look appropriate for our needs but I haven't been able to find much useful info on it ([metadata](https://www.arcgis.com/sharing/rest/content/items/4bd9b6892530404abfe13645fcb5099a/info/metadata/metadata.xml?format=default&output=html)).

NationalMap has NHD and NHDPlus_HR but neither of them match what's available from ESRI. NHD has the black dots in the previous image which wouldn't have helped in this case, and in the image below NHDPlus_HR ([NHDPlusSink layer](https://hydro.nationalmap.gov/arcgis/rest/services/NHDPlus_HR/MapServer/1) -- only "network ends" are shown) are the green dots (which interestingly don't align with all of the ESRI points), both of which could be used to clip the DEM-derived stream, although at first glance the density of NHDPlus_HR points will introduce problems with level paths.
<img width="630" alt="image" src="https://user-images.githubusercontent.com/6616694/228056330-bae41664-a125-441d-80c3-19456a236c93.png">

**Comment by CarsonPruitt-NOAA** [comment]
After reading a little more into things, it seems like the NWM is using the "legacy" NHD, which is actually now managed by EPA. See the bottom of [this page](https://www.usgs.gov/national-hydrography/national-hydrography-dataset).  The [EPA NHD website](https://www.epa.gov/waterdata/nhdplus-national-hydrography-dataset-plus) has a place to download the data. Can you download a HUC and confirm that it's got the same streamlines as our NWM dataset and that the sinks match what we're seeing in the ESRI service.

We definitely DON'T want to use the NHD HR dataset since the NWM streamlines are based on the medium-res. Another important note: the issue that spawned this ticket is in branch 0, so we want to make sure that we're not limiting this workflow to the level paths.

**Comment by mluck** [comment]
The [legacy NHD data from the EPA](https://www.epa.gov/waterdata/nhdplus-national-data) (orange dots) do match the ESRI sinks (circles) and seem to agree with the NWM data (blue; DEM-derived reaches in green). There is an error in the NHDFlowline so I haven't been able to compare those directly yet.
<img width="630" alt="image" src="https://user-images.githubusercontent.com/6616694/228259062-aa0a15f6-ed9f-4113-82d6-9890e1be5733.png">

**Comment by mluck** [comment]
To document, the links to the EPA sinks data came from https://www.epa.gov/waterdata/nhdplus-national-data:
- [NHDPlusV21_NationalData_Seamless_Geodatabase_Lower48_07.7z](https://edap-ow-data-commons.s3.amazonaws.com/NHDPlusV21/Data/NationalData/NHDPlusV21_NationalData_Seamless_Geodatabase_Lower48_07.7z)
- [NHDPlusV21_NationalData_Seamless_Geodatabase_HI_PR_VI_PI_03.7z](https://edap-ow-data-commons.s3.amazonaws.com/NHDPlusV21/Data/NationalData/NHDPlusV21_NationalData_Seamless_Geodatabase_HI_PR_VI_PI_03.7z)

**Comment by mluck** [comment]
Branch 0 is now clipped to terminal NWM stream segments (i.e., where `to=0`) (DEM-derived branch 0 in green; NWM streams in blue; terminal NWM stream segments in black; black points are NHD sinks)

HUC 18060002 (compare this to the image above)
<img width="336" alt="image" src="https://user-images.githubusercontent.com/6616694/230629759-74200e8b-aa51-4318-ad1d-d9fbe8319f0a.png">

HUC 14030003 (notice the terminal NWM segments are not associated with sinks)
<img width="336" alt="image" src="https://user-images.githubusercontent.com/6616694/230629868-f411c77a-9e2b-4b8b-b837-0b475a83ce56.png">

It looks like the right stream might be wrong, but a closer look shows that there is a 2.5 m difference between the two segments which is greater than the 1m snapping threshold, so this is acceptable behavior
<img width="336" alt="image" src="https://user-images.githubusercontent.com/6616694/230629929-d9c33996-23fc-41ea-b49d-3ea4a243b2cb.png">
